### PR TITLE
#32 Get entry info

### LINKED ISSUE #32: Get entry info.
:information_source: This issue is part of the Epic #12.

### Objective
Create a module to get single entry info from the Tickspot API.

Documentation:
- [Get entry](https://github.com/tick/tick-api/blob/master/sections/entries.md#get-entry).

### CheckList
- [x] Create a method to get an entry.
- [x] Create tests.

### PR DESCRIPTION
**Pull request by MrJuanGaviriaK**
Closes #32

### CODE REVIEW

**Review by brayvasq — COMMENTED** [review]
:wave: Hi @MrJuanGaviriaK Thanks for your contribution, nice work. The changes seems to be ok. But talking with @JoseCastroA, we noticed that 'fixtures' seem to be a bit ambiguous, eg `createResponse` doesn't represent what it was actually created for. So we're wondering if you don't mind us adding a few changes to the 'fixtures' in this PR. What do you think?

**Comment by MrJuanGaviriaK** [comment]
Hi @brayvasq 
Yes, of course, what changes do we need to add?

**Comment by MrJuanGaviriaK** [comment]
Hi @brayvasq  and @JoseCastroA 

I worked on restructuring the test folder, I'm going to wait for your feedback!!!

Thanks

**Review by brayvasq — APPROVED** [review]
:rocket:

**Pull request merged**
